### ISSUE TITLE
[CI][Bug] Latest merged(!) commits have failing checks

### ISSUE THREAD

**Issue by abebeos** [aptos-labs/aptos-core#6941]
# Bug

## To reproduce

See https://github.com/aptos-labs/aptos-core/commits/main

Example: https://github.com/aptos-labs/aptos-core/actions/runs/4338849517/jobs/7575891025#step:5:2201

## Expected Behavior

All checks pass, a green "Checkmark" symbol is shown instead of the red "X"

## Additional context

The quick solution should be to disable:

https://github.com/aptos-labs/aptos-core/actions/runs/4338849517/workflow#L104-L112

or to possibly add a check to avoid running the failing step.

## Prevention

Similar incidents can be avoided in future by:

- https://github.com/aptos-labs/aptos-core/issues/6943

**Simple Rule: No Green, No Merge!**

## Possibly Related

- #6930

**Comment by ibalajiarun** [comment]
Fixed in https://github.com/aptos-labs/aptos-core/pull/6979.

**Comment by abebeos** [comment]
> Fixed in #6979.

This is not fixed, as it is a systemic problem (further elaborations within #6943)
